---
- name: provision lamp stack
  hosts: all
  become: yes

  tasks:
  - name: install lamp
    package:
      name: "{{ item }}"
      state: installed
    with_items:
    - httpd
    - mariadb
    - php
